# Generated by Django 3.2.10 on 2022-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_auto_20220125_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='describe',
            field=models.TextField(default='', null=True, verbose_name='描述'),
        ),
    ]
