# Generated by Django 4.0.2 on 2022-04-17 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0009_alter_module_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app_api.project'),
            preserve_default=False,
        ),
    ]
