# Generated by Django 4.0.2 on 2022-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0010_testtask_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcaserelevance',
            name='module_id',
            field=models.IntegerField(default=0),
        ),
    ]
