# Generated by Django 4.0.2 on 2022-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0011_taskcaserelevance_module_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcaserelevance',
            name='case',
        ),
        migrations.AddField(
            model_name='taskcaserelevance',
            name='cases',
            field=models.TextField(null=True),
        ),
    ]
