# Generated by Django 4.0.2 on 2022-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0012_remove_taskcaserelevance_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=50, null=True, verbose_name='图片'),
        ),
    ]
